<?php
        $apiKey="rzp_test_VqWHeX7pY73YLm";
        include 'dbconnect.php';
        $total=$_GET['amount'];
        $oid=$_GET['oid']; 
        $select =mysqli_query($con,"SELECT * FROM `offense committed` WHERE `O_R_id`='$oid'");
        $rows=mysqli_fetch_array($select);
             
?>

                                        


<form action="payaction.php?oid=<?php echo $oid;?>" method="post">
<script
    src="https://checkout.razorpay.com/v1/checkout.js"
    data-key="<?php echo $apiKey; ?>" // Enter the Test API Key ID generated from Dashboard → Settings → API Keys
    data-amount="<?php echo $total * 100; ?>" // Amount is in currency subunits. Hence, 29935 refers to 29935 paise or ₹299.35.
    data-currency="INR"// You can accept international payments by changing the currency code. Contact our Support Team to enable International for your account
    data-order_id="<?php rand(100000, 999999);?>"// Replace with the order_id generated by you in the backend.
    data-buttontext="Pay"
    data-name="Traffic Squard"
    data-description="Traffic Offence Reporting Website"
    data-image=""
    data-prefill.name=""
    data-prefill.email=""
    data-theme.color="#F37254"
></script>
<input type="hidden" custom="Hidden Element" name="hidden">
</form>
<script>

  setTimeout(() => {

    document.getElementsByClassName('razorpay-payment-button')[0].click();

  }, 500);

</script>

<!--style>
.razorpay-payment-button { display:none; }
</style>


<script type="text/javascript">
  $(document).ready(function(){
    $('.razorpay-payment-button').click();

});
</script-->